In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [127]:
df=pd.read_csv('amazon.csv')
print(df)
df.head()

      product_id                                       product_name  \
0     B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...
1     B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2     B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...
3     B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4     B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...
...          ...                                                ...
1460  B08L7J3T31  Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1461  B01M6453MB  Prestige Delight PRWO Electric Rice Cooker (1 ...
1462  B009P2LIL4  Bajaj Majesty RX10 2000 Watts Heat Convector R...
1463  B00J5DYCCA  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1464  B01486F4G6  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...

                                               category discounted_price  \
0     Computers&Accessories|Accessories&Peripherals|...             ₹399
1     Computers&Accessories|Accessories&Peripherals|...             ₹199
2     Computers&Accessories|Accessories&Peripherals|...             ₹199
3     Computers&Accessories|Accessories&Peripherals|...             ₹329
4     Computers&Accessories|Accessories&Peripherals|...             ₹154
...                                                 ...              ...
1460  Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...             ₹379
1461  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,280
1462  Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...           ₹2,219
1463  Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...           ₹1,399
1464  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,863

     actual_price discount_percentage rating rating_count  \
0          ₹1,099                 64%    4.2       24,269
1            ₹349                 43%    4.0       43,994
2          ₹1,899                 90%    3.9        7,928
3            ₹699                 53%    4.2       94,363
4            ₹399                 61%    4.2       16,905
...           ...                 ...    ...          ...
1460         ₹919                 59%      4        1,090
1461       ₹3,045                 25%    4.1        4,118
1462       ₹3,080                 28%    3.6          468
1463       ₹1,890                 26%      4        8,031
1464       ₹3,690                 22%    4.3        6,987

                                          about_product  \
0     High Compatibility : Compatible With iPhone 12...
1     Compatible with all Type C enabled devices, be...
2     【 Fast Charger& Data Sync】-With built-in safet...
3     The boAt Deuce USB 300 2 in 1 cable is compati...
4     [CHARGE & SYNC FUNCTION]- This cable comes wit...
...                                                 ...
1460  SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...
1461                       230 Volts, 400 watts, 1 Year
1462  International design and styling|Two heat sett...
1463  Fan sweep area: 230 MM ; Noise level: (40 - 45...
1464  Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...

                                                user_id  \
0     AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
1     AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...
2     AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...
3     AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...
4     AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...
...                                                 ...
1460  AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...
1461  AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...
1462  AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...
1463  AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...
1464  AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...

                                              user_name  \
0     Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
1     ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...
2     Kunal,Himanshu,viswanath,sai niharka,saqib mal...
3     Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...
4     rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...
...                                                 ...
1460  Prabha ds,Raghuram bk,Real Deal,Amazon Custome...
1461  Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...
1462  Nehal Desai,Danish Parwez,Amazon Customer,Amaz...
1463  Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...
1464  Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...

                                              review_id  \
0     R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
1     RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...
2     R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...
3     R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...
4     R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...
...                                                 ...
1460  R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...
1461  R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...
1462  R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...
1463  R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...
1464  R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...

                                           review_title  \
0     Satisfied,Charging is really fast,Value for mo...
1     A Good Braided Cable for Your Type C Device,Go...
2     Good speed for earlier versions,Good Product,W...
3     Good product,Good one,Nice,Really nice product...
4     As good as original,Decent,Good one for second...
...                                                 ...
1460  Received the product without spanner,Excellent...
1461  ok,everything was good couldn't return bcoz I ...
1462  very good,Work but front melt after 2 month,Go...
1463  Fan Speed is slow,Good quality,Good product,go...
1464  Works perfect,Ok good product,Nice Product. Re...

                                         review_content  \
0     Looks durable Charging is fine tooNo complains...
1     I ordered this cable to connect my phone to An...
2     Not quite durable and sturdy,https://m.media-a...
3     Good product,long wire,Charges good,Nice,I bou...
4     Bought this instead of original apple, does th...
...                                                 ...
1460  I received product without spanner,Excellent p...
1461  ok,got everything as mentioned but the measuri...
1462  plastic but cool body ,u have to find sturdy s...
1463  I have installed this in my kitchen working fi...
1464  It does it job perfectly..only issue is temp c...

                                               img_link  \
0     https://m.media-amazon.com/images/W/WEBP_40237...
1     https://m.media-amazon.com/images/W/WEBP_40237...
2     https://m.media-amazon.com/images/W/WEBP_40237...
3     https://m.media-amazon.com/images/I/41V5FtEWPk...
4     https://m.media-amazon.com/images/W/WEBP_40237...
...                                                 ...
1460  https://m.media-amazon.com/images/I/41fDdRtjfx...
1461  https://m.media-amazon.com/images/I/41gzDxk4+k...
1462  https://m.media-amazon.com/images/W/WEBP_40237...
1463  https://m.media-amazon.com/images/W/WEBP_40237...
1464  https://m.media-amazon.com/images/W/WEBP_40237...

                                           product_link
0     https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1     https://www.amazon.in/Ambrane-Unbreakable-Char...
2     https://www.amazon.in/Sounce-iPhone-Charging-C...
3     https://www.amazon.in/Deuce-300-Resistant-Tang...
4     https://www.amazon.in/Portronics-Konnect-POR-1...
...                                                 ...
1460  https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461  https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462  https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463  https://www.amazon.in/Havells-Ventilair-230mm-...
1464  https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

[1465 rows x 16 columns]

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [128]:
df.shape

(1465, 16)

In [129]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='object')

In [130]:
df.dtypes

product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

In [131]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [132]:
df.tail()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [134]:
df.describe()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
count,1465,1465,1465,1465,1465,1465,1465,1463,1465,1465,1465,1465,1465,1465,1465,1465
unique,1351,1337,211,550,449,92,28,1143,1293,1194,1194,1194,1194,1212,1412,1465
top,B083342NKJ,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,50%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
freq,3,5,233,53,120,56,244,9,6,10,10,10,10,8,3,1

In [135]:
#Detect missing values
df.isna().any()

product_id             False
product_name           False
category               False
discounted_price       False
actual_price           False
discount_percentage    False
rating                 False
rating_count            True
about_product          False
user_id                False
user_name              False
review_id              False
review_title           False
review_content         False
img_link               False
product_link           False
dtype: bool

In [136]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [137]:

# 1. Convert the column to numbers.
# errors='coerce' turns any text (like '1.2k') into NaN so it doesn't crash.
df["rating_count"] = pd.to_numeric(df["rating_count"], errors="coerce")
# 2. Now fill the NaN values with the mean
df["rating_count"].fillna(df["rating_count"].mean(), inplace=True)

/tmp/ipython-input-1099536516.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["rating_count"].fillna(df["rating_count"].mean(), inplace=True)

In [138]:
print(df["rating_count"])

0       348.217791
1       348.217791
2       348.217791
3       348.217791
4       348.217791
           ...
1460    348.217791
1461    348.217791
1462    468.000000
1463    348.217791
1464    348.217791
Name: rating_count, Length: 1465, dtype: float64

In [139]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [140]:
# Convert the column to string type first
df["discounted_price"] = df["discounted_price"].astype(str)
df['actual_price'] = df['actual_price'].astype(str)

# Then apply the replace and conversion
df["discounted_price"] = df["discounted_price"].str.replace("₹", "").str.replace(",", "").astype(float)
df['actual_price'] = df['actual_price'].str.replace("₹", "").str.replace(",", "").astype(float)

In [141]:
# Convert to string first
df['discount_percentage'] = df['discount_percentage'].astype(str)

# Then remove '%' and convert to float
df['discount_percentage'] = df['discount_percentage'].str.replace('%', '').astype(float)
df['discount_percentage']

0       64.0
1       43.0
2       90.0
3       53.0
4       61.0
        ...
1460    59.0
1461    25.0
1462    28.0
1463    26.0
1464    22.0
Name: discount_percentage, Length: 1465, dtype: float64

In [142]:
#clean Rating :some rows might have invalid chars like '|'replace them
# Convert to string first
df['rating']= df['rating'].astype(str)
df['rating_count']= df['rating_count'].astype(str)
df['rating']=pd.to_numeric(df['rating'],errors='coerce')
df['rating_count']=df['rating_count'].str.replace(',','').astype(float)
df['rating_count']

0       348.217791
1       348.217791
2       348.217791
3       348.217791
4       348.217791
           ...
1460    348.217791
1461    348.217791
1462    468.000000
1463    348.217791
1464    348.217791
Name: rating_count, Length: 1465, dtype: float64

In [143]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,348.217791,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43.0,4.0,348.217791,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90.0,3.9,348.217791,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0,4.2,348.217791,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,4.2,348.217791,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [144]:
df.drop(columns=['discount_percentage','user_id',	'user_name',	'review_id',	'review_title','review_content','img_link','product_link'],axis=1,inplace=True)

In [145]:
df.drop(columns=[	'product_id','product_name'],axis=1,inplace=True)

In [146]:
df.drop(columns=[	'about_product'],axis=1,inplace=True)

In [147]:
df.head()

,category,discounted_price,actual_price,rating,rating_count
0,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,4.2,348.217791
1,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,4.0,348.217791
2,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,3.9,348.217791
3,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,4.2,348.217791
4,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,4.2,348.217791

In [148]:
df.shape

(1465, 5)

In [149]:
df['category']=df['category'].str.split('|').str[0]

In [150]:
df=pd.get_dummies(df,columns=['category'],drop_first=True,dtype=int)

In [151]:
df.head()

,discounted_price,actual_price,rating,rating_count,category_Computers&Accessories,category_Electronics,category_Health&PersonalCare,category_Home&Kitchen,category_HomeImprovement,category_MusicalInstruments,category_OfficeProducts,category_Toys&Games
0,399.0,1099.0,4.2,348.217791,1,0,0,0,0,0,0,0
1,199.0,349.0,4.0,348.217791,1,0,0,0,0,0,0,0
2,199.0,1899.0,3.9,348.217791,1,0,0,0,0,0,0,0
3,329.0,699.0,4.2,348.217791,1,0,0,0,0,0,0,0
4,154.0,399.0,4.2,348.217791,1,0,0,0,0,0,0,0

In [152]:
x=df.drop('rating',axis=1)
y=df['rating']

In [153]:
df.shape

(1465, 12)

In [154]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(y_train.shape)

(1172, 11)
(1172,)

In [155]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [156]:
#Define the model of ANN
from keras.models import Sequential
from keras.layers import Dense

In [166]:
classifier=Sequential()

In [167]:
classifier.add(Dense(units=6,activation='relu',input_dim=11))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [168]:
classifier.add(Dense(units=6,activation='relu'))

In [160]:
classifier.add(Dense(units=1,activation='sigmoid'))

In [161]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [164]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1172, 11)
(1172,)
(293, 11)
(293,)

In [162]:
model_history=classifier.fit(x_train,y_train,batch_size=11,epochs=25,validation_split=0.33)

Epoch 1/25

ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_10" is incompatible with the layer: expected axis -1 of input shape to have value 10, but received input with shape (None, 11)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 11), dtype=float32)
  • training=True
  • mask=None
  • kwargs=<class 'inspect._empty'>